### ISSUE TITLE
Very strange code, what is that means?

### ISSUE THREAD

**Issue by JoneDoe** [nnrudakov/yii2-sms#2]
if (!\count($response->errors->children())) 

> /src/sms/services/beeline/Beeline.php line 140

**Comment by nnrudakov** [comment]
it checks for errors in response.
for new protocol version it will be deleted. errors handling will be changed

**Comment by JoneDoe** [comment]
where can I find new protocol. Now I have problems with this;

**Comment by JoneDoe** [comment]
I mean what is this?? 
`!\count`

**Comment by nnrudakov** [comment]
you can ask your Beeline manager for a new docs.

code means, if count of errors equals 0 then exit from method. and it means there are no errors in response

**Comment by JoneDoe** [comment]
realy )))) why you put **backslash**  between _!_ and _count_

**Comment by nnrudakov** [comment]
because this is exclude `INIT_NS_FCALL_BY_NAME`. this is one of the many optimizations applied by PHP 7 and newer versions (see [zend_compile.c](https://github.com/php/php-src/blob/PHP-7.1/Zend/zend_compile.c) for more examples)
